### PR TITLE
Add dynamic role option

### PR DESCRIPTION
**Pull request by MichaelErmer**
### Summary

Add option to use the services path as a "dynamic" role, this is a new attempt to solve #25

### CODE REVIEW

**Comment by daffl** [comment]
This makes sense, thank you for the PR. I think a slightly nicer API (instead of an additional option) would be to allow a function that takes the `context` to be passed as `roles`:

```js
app.service('messages').hooks({
  before: checkPermissions({
    roles(context) {
      return [ 'admin', context.path ];
    }
  })
});
```

**Comment by MichaelErmer** [comment]
Nope, the point of that options is that it can be applied to the global hooks.

**Comment by MichaelErmer** [comment]
@daffl very nice

**Comment by daffl** [comment]
Released with #37 as v0.2.1. Thank you!

**Pull request merged**
